:repository-owner: arduino-libraries
:repository-name: ArduinoRS485

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

Enables sending and receiving data using the RS-485 standard with RS-485 shields, like the MKR 485 Shield.

This library supports the Maxim Integrated MAX3157 and equivalent chipsets.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/{repository-name}

# Hardware Preparations

Hardwre needed: We will prepare two sets of each solution.

## USB Solution 

* USB Cable
* RS485 (XXX add model)
* ...

We will plug in two USBs to a laptop computer.
TODO Add photo.

## Arduino Solution

* Arduino XX
* MKR RS485 Shield
* Embedded Computer or PC

# Use Case 1: Send and Receive

The use case aims at verifying that the RS485 hardware is functional.
Two sets of hardware will send and receive from each other.

TODO: add Dockerfile for laptop, pytest 

## Use Case 1.1: Two Sets of USB + RS485

## Use Case 1.2: Two Sets of Arduino + MKR RS485 Shield Testing
